[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"
rustflags = [
    "-C", "relocation-model=pic",
    "-C", "link-args=-Wl,-z,max-page-size=16384 -Wl,-z,common-page-size=16384",
    "-C", "link-args=-Wl,--pack-dyn-relocs=android",
    "-C", "link-args=-Wl,--hash-style=both",
    "-C", "link-args=-Wl,-z,relro -Wl,-z,now"
]

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi21-clang"
# 32-bit targets do not need 16 KB alignment; page size remains 4 KB
rustflags = [
    "-C", "relocation-model=pic",
    "-C", "link-args=-Wl,--hash-style=both",
    "-C", "link-args=-Wl,--pack-dyn-relocs=android"
]

[target.i686-linux-android]
linker = "i686-linux-android21-clang"
rustflags = [
    "-C", "relocation-model=pic",
    "-C", "link-args=-Wl,--hash-style=both",
    "-C", "link-args=-Wl,--pack-dyn-relocs=android"
]

[target.x86_64-linux-android]
linker = "x86_64-linux-android21-clang"
rustflags = [
    "-C", "relocation-model=pic",
    "-C", "link-args=-Wl,-z,max-page-size=16384 -Wl,-z,common-page-size=16384",
    "-C", "link-args=-Wl,--pack-dyn-relocs=android",
    "-C", "link-args=-Wl,--hash-style=both"
]